### ISSUE TITLE
The plugin is not loading due to newest update

### ISSUE THREAD

**Issue by PaBox** [Dart2112/AFKPlusPAPI#8]
Same error as Issue #5 

[04:21:59 ERROR]: Error occurred while enabling AFKPlusPAPI v1.0.4 (Is it up to date?)
mc-minigames-server               | java.lang.NoClassDefFoundError: net/lapismc/lapiscore/placeholder/PlaceholderAPIExpansion
mc-minigames-server               |     at java.base/java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
mc-minigames-server               |     at java.base/java.lang.ClassLoader.defineClass(Unknown Source) ~[?:?]
mc-minigames-server               |     at java.base/java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:?]
mc-minigames-server               |     at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:243) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
mc-minigames-server               |     at java.base/java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
mc-minigames-server               |     at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:169) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
mc-minigames-server               |     at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
mc-minigames-server               |     at java.base/java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
mc-minigames-server               |     at AFKPlusPAPI.jar/net.lapismc.afkpluspapi.AFKPlusPAPI.onEnable(AFKPlusPAPI.java:11) ~[AFKPlusPAPI.jar:?]
mc-minigames-server               |     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
mc-minigames-server               |     at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.20.6.jar:1.20.6-149-6e71f41]
mc-minigames-server               |     at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.6.jar:1.20.6-149-6e71f41]
mc-minigames-server               |     at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
mc-minigames-server               |     at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:626) ~[paper-1.20.6.jar:1.20.6-149-6e71f41]
mc-minigames-server               |     at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:575) ~[paper-1.20.6.jar:1.20.6-149-6e71f41]
mc-minigames-server               |     at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:675) ~[paper-1.20.6.jar:1.20.6-149-6e71f41]
mc-minigames-server               |     at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[paper-1.20.6.jar:1.20.6-149-6e71f41]
mc-minigames-server               |     at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:323) ~[paper-1.20.6.jar:1.20.6-149-6e71f41]
mc-minigames-server               |     at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1136) ~[paper-1.20.6.jar:1.20.6-149-6e71f41]
mc-minigames-server               |     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-149-6e71f41]
mc-minigames-server               |     at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]
mc-minigames-server               | Caused by: java.lang.ClassNotFoundException: net.lapismc.lapiscore.placeholder.PlaceholderAPIExpansion
mc-minigames-server               |     at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
mc-minigames-server               |     at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
mc-minigames-server               |     at java.base/java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
mc-minigames-server               |     ... 21 more

**Comment by Dart2112** [comment]
It was an error with the way that AFKPlus was deployed to the Maven repo without the class remapping applied, it's now been fixed and a new release of the PAPI extension is on the way.
